abandoning modularity for the moment

diff --git a/.github/workflows/my-git-action-II.yml b/.github/workflows/my-git-action-II.yml
--- a/.github/workflows/my-git-action-II.yml
+++ b/.github/workflows/my-git-action-II.yml
@@ -3,31 +3,46 @@
 #Github actions
 #
 #-----------------------------------
-name: My Main Workflow
+name: Introducing workflow 
 
 on:
   push:
-    branches: [main]
+    branches: [main, master]
+  workflow_call:
+   secrets:
+    MY_API_KEY:
+      required: true
 
 jobs:
-  # Step 1: Call the reusable workflow
-  call-reusable-workflow:
-    uses: .github/workflows/my-git-action.yml
-    secrets:
-      MY_API_KEY: ${{ secrets.MY_API_KEY }}
-
-  # Step 2: Next job that depends on the reusable workflow
-  next-job:
+  my-testing-II:
     runs-on: ubuntu-latest
-    needs: call-reusable-workflow
     steps:
-      - name: Run after reusable workflow
-        run: echo "This runs after my-git-action.yml finished"
+        - run: echo "this is a test"
+#    uses: .github/workflows/my-git-action.yml
 
-  # Step 3: Another job after previous job
-  deploy-job:
+  my-testing-III:
     runs-on: ubuntu-latest
-    needs: next-job
+    needs: my-testing-II
     steps:
-      - name: Deploy step
-        run: echo "Deploying after previous jobs"
+      - run: echo "This runs after my-git-action.yml finishes"
+
+  my_deploy_second_machine:
+    runs-on: ubuntu-latest
+    needs: [my-testing-II, my-testing-III]
+    steps:
+      - run: echo "Hello from deploy job"
+
+  my_deploy_secret:
+    runs-on: ubuntu-latest
+    needs: my_deploy_second_machine
+    steps:
+      - name: Check secret
+        run: |
+          if [ -z "$MY_API_KEY" ]; then
+            echo "Secret missing"
+            exit 1
+          else
+            echo "Secret loaded"
+          fi
+        env:
+          MY_API_KEY: ${{ secrets.MY_API_KEY }}
