workflow

diff --git a/.github/workflows/my-git-action-II.yml b/.github/workflows/my-git-action-II.yml
--- a/.github/workflows/my-git-action-II.yml
+++ b/.github/workflows/my-git-action-II.yml
@@ -3,20 +3,11 @@
 #Github actions
 #
 #-----------------------------------
-name: My-Multiple-Github-Actions
-
+name: My Main Workflow
 
 on:
-    push:
-      branches: [main, master]
-    workflow_call:
-        inputs:
-         environment:
-           required: true
-           type: string
-
-
-  
+  push:
+    branches: [main, master]
 
 jobs:
   my-testing-II:
@@ -34,17 +25,16 @@ jobs:
       - run: echo "Hello from deploy job"
 
   my_deploy_secret:
-   runs-on: ubuntu-latest
-   needs: my_deploy_second_machine
-
-   steps:
-    - name: Check secret
-      run: |
-        if [ -z "$MY_API_KEY" ]; then
-          echo "Secret missing"
-          exit 1
-        else
-          echo "Secret loaded"
-        fi
-      env:
-        MY_API_KEY: ${{ secrets.MY_API_KEY }}
+    runs-on: ubuntu-latest
+    needs: my_deploy_second_machine
+    steps:
+      - name: Check secret
+        run: |
+          if [ -z "$MY_API_KEY" ]; then
+            echo "Secret missing"
+            exit 1
+          else
+            echo "Secret loaded"
+          fi
+        env:
+          MY_API_KEY: ${{ secrets.MY_API_KEY }}
