important yaml files only

diff --git a/.github/workflows/my-git-action-II.yml b/.github/workflows/my-git-action-II.yml
--- a/.github/workflows/my-git-action-II.yml
+++ b/.github/workflows/my-git-action-II.yml
@@ -1,53 +1,53 @@
-#-----------------------------------
-#
-#Github actions
-#
-#-----------------------------------
-name: Introducing workflow 
+# #-----------------------------------
+# #
+# #Github actions
+# #
+# #-----------------------------------
+# name: Introducing workflow 
 
-on:
-  push:
-    branches: [main, master]
-  workflow_call:
-   secrets:
-    MY_API_KEY:
-      required: true
+# on:
+#   push:
+#     branches: [main, master]
+#   workflow_call:
+#    secrets:
+#     MY_API_KEY:
+#       required: true
 
-jobs:
-  deploiment-to-Dev:
-    runs-on: ubuntu-latest
-    steps:
-        - run: echo "this will diploy the code on Dev env"
-  my-testing-II:
-    needs: deploiment-to-Dev
-    runs-on: ubuntu-latest
-    steps:
-        - run: echo "this is a test"
-#    uses: .github/workflows/my-git-action.yml
+# jobs:
+#   deploiment-to-Dev:
+#     runs-on: ubuntu-latest
+#     steps:
+#         - run: echo "this will diploy the code on Dev env"
+#   my-testing-II:
+#     needs: deploiment-to-Dev
+#     runs-on: ubuntu-latest
+#     steps:
+#         - run: echo "this is a test"
+# #    uses: .github/workflows/my-git-action.yml
 
-  my-testing-III:
-    runs-on: ubuntu-latest
-    needs: my-testing-II
-    steps:
-      - run: echo "This runs after my-git-action.yml finishes"
+#   my-testing-III:
+#     runs-on: ubuntu-latest
+#     needs: my-testing-II
+#     steps:
+#       - run: echo "This runs after my-git-action.yml finishes"
 
-  my_deploy_second_machine:
-    runs-on: ubuntu-latest
-    needs: [my-testing-II, my-testing-III]
-    steps:
-      - run: echo "Hello from deploy job"
+#   my_deploy_second_machine:
+#     runs-on: ubuntu-latest
+#     needs: [my-testing-II, my-testing-III]
+#     steps:
+#       - run: echo "Hello from deploy job"
 
-  my_deploy_secret:
-    runs-on: ubuntu-latest
-    needs: my_deploy_second_machine
-    steps:
-      - name: Check secret
-        run: |
-          if [ -z "$MY_API_KEY" ]; then
-            echo "Secret missing"
-            exit 1
-          else
-            echo "Secret loaded"
-          fi
-        env:
-          MY_API_KEY: ${{ secrets.MY_API_KEY }}
+#   my_deploy_secret:
+#     runs-on: ubuntu-latest
+#     needs: my_deploy_second_machine
+#     steps:
+#       - name: Check secret
+#         run: |
+#           if [ -z "$MY_API_KEY" ]; then
+#             echo "Secret missing"
+#             exit 1
+#           else
+#             echo "Secret loaded"
+#           fi
+#         env:
+#           MY_API_KEY: ${{ secrets.MY_API_KEY }}
